=== arximboldi/jagsat/doc/file-formats/map-file.dtd
<!--
   
   This is the DTD definition file for the map files in the Jagsat
   project for the Project Course in Ã‚bo Akademy.
   
   (c) The Jagsat Development Team 2009

-->

<!-- 

   Root element. The attribute 'bg' is the relative path to the
   background image and is compulsory

   TODO: These attributes should be better moved to meta.

-->
<!ELEMENT map (meta?,(continent|link)*)>
<!ATTLIST map
	  bg CDATA #REQUIRED
	  zoom CDATA #IMPLIED
	  xscale CDATA #IMPLIED
	  yscale CDATA #IMPLIED
	  xoffset CDATA #IMPLIED
	  yoffset CDATA #IMPLIED>

<!-- 

   Meta-information about the map that can be used in the map selector
   or just for credit purposes.

-->
<!ELEMENT meta (author?, description?, title?, thumbnail?)>
<!ELEMENT author (#PCDATA)> 
<!ELEMENT thumbnail (#PCDATA)> 
<!ELEMENT description (#PCDATA)>
<!ELEMENT title (#PCDATA)>

<!-- 

   A continent is a group of regions. It may contain a unique 'name'
   attribute that gives a referentiable and showable name for
   it. Also, it may contain a 'troops' parameter that indicates the
   number of reinforcements that owning this continent rewards the
   player.

-->
<!ELEMENT continent (region*)>
<!ATTLIST continent
	  name   CDATA #IMPLIED
	  troops CDATA "0">

<!--

   A region is a country or a delimited area that the player can
   own. Its click area can be defined by either a circle or a
   polygon. The optional 'name' parameter can be used to give it a
   unique name to reference it in the linkions.

-->
<!ELEMENT region (point|circle|polygon)>
<!ATTLIST region
	  name CDATA #IMPLIED>

<!--

   A circle is defined by a point and a radius. The 'radius' is an
   attribute while the center must be specified using a point.

-->
<!ELEMENT circle (point)>
<!ATTLIST circle
	  radius CDATA #IMPLIED>

<!--
   
   A poligon defined by the sequence of points that determine its
   frontier polyline.

-->
<!ELEMENT polygon (point*)>

<!--

   A point must contain an 'x' and 'y' attribute defining its absolute
   coordinates.

-->
<!ELEMENT point EMPTY>
<!ATTLIST point
	  x CDATA "0"
	  y CDATA "0">

<!--
   
   Use 'link' to link several regions so they can be considered
   nerby countries and units can move between them. Note that all the
   linkions are bi-directional. It contains a sequence of
   nodes. Depending on the value of the 'type' attribute this will
   behave:

   - line: The given nodes are going to be sequentially. For example,
   if the nodes named 'a', 'b', 'c' and 'd' are given, the following
   set of linkions will be created: 'a-b, b-c, c-d'
   
   - circle: Same as line, but the last and first nodes are
   linked. In the previous example, 'a-b, b-c, c-d, d-a' links
   would be created.

   - pairs: The links would be created in pair. In the previous
   example, 'a-b, c-d' links would be created.

   - clique: The given nodes are linked to form a clique or
   complete graph. In the previus example, 'a-b, a-c, a-d, b-c, b-d,
   c-d' would be created.

-->
<!ELEMENT link (node*)>
<!ATTLIST link 
	  type (line|circle|pairs|clique) "line">
<!ELEMENT node EMPTY>
<!ATTLIST node 
	  name CDATA #REQUIRED>

=== arximboldi/jagsat/doc/map/solarsystem.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map SYSTEM "file:../file-formats/map-file.dtd">

<map bg="doc/map/solarsystem.png" 
     xscale="4" yscale="2.8" xoffset="0" yoffset="150" zoom="2">
  <meta>
    <author>The JAGSAT Development team.</author>
    <description>solarsystem map.</description>
  </meta>

  <!-- continent mercury, venus, tellus -->

  <continent name="mercury venus and tellus"
	     troops="4">
    <region name="mercury">
      <circle>
	<point x="46" y="75"/>
      </circle>
    </region>
    <region name="venus1">
      <circle>
	<point x="60" y="65"/>
      </circle>
    </region>
    <region name="venus2">
      <circle>
	<point x="60" y="40"/>
      </circle>
    </region>
    <region name="tellus1">
      <circle>
	<point x="79" y="52"/>
      </circle>
    </region>
    <region name="tellus2">
      <circle>
	<point x="79" y="27"/>
      </circle>
    </region>
  </continent>

  <!-- continent mars and jupiter -->

  <continent name="mars and jupiter"
	     troops="5">
    <region name="mars1">
      <circle>
	<point x="92" y="10"/>
      </circle>
    </region>
    <region name="mars2">
      <circle>
	<point x="92" y="33"/>
      </circle>
    </region>
    <region name="jupiter1">
      <circle>
	<point x="125" y="30"/>
      </circle>
    </region>
    <region name="jupiter2">
      <circle>
	<point x="118" y="5"/>
      </circle>
    </region>
    <region name="jupiter3">
      <circle>
	<point x="130" y="5"/>
      </circle>
    </region>
    <region name="jupiter4">
      <circle>
	<point x="118" y="55"/>
      </circle>
    </region>   
    <region name="jupiter5">
      <circle>
	<point x="130" y="55"/>
      </circle>
    </region>
  </continent>

  <!-- continent saturn and uranus -->

  <continent name="saturn and uranus"
	     troops="5">

    <region name="saturn1">
      <circle>
	<point x="155" y="-5"/>
      </circle>
    </region>
    <region name="saturn2">
      <circle>
	<point x="168" y="5"/>
      </circle>
    </region>
    <region name="saturn3">
      <circle>
	<point x="155" y="18"/>
      </circle>
    </region>
    <region name="uranus1">
      <circle>
	<point x="180" y="-25"/>
      </circle>
    </region>
    <region name="uranus2">
      <circle>
	<point x="188" y="-15"/>
      </circle>
    </region>   
    <region name="uranus3">
      <circle>
	<point x="180" y="-5"/>
      </circle>
    </region>
  </continent>


  <!-- continent deathstar, neputune, pluto -->

  <continent name="deathstar nepute and pluto"
	     troops="4">
    <region name="deathstar1">
      <circle>
	<point x="220" y="25"/>
      </circle>
    </region>
    <region name="deathstar2">
      <circle>
	<point x="210" y="10"/>
      </circle>
    </region>
    <region name="deathstar3">
      <circle>
	<point x="210" y="30"/>
      </circle>
    </region>
    <region name="neptune1">
      <circle>
	<point x="199" y="-39"/>
      </circle>
    </region>   
   <region name="neptune2">
      <circle>
	<point x="207" y="-15"/>
      </circle>
    </region>
    <region name="pluto">
      <circle>
	<point x="220" y="-30"/>
      </circle>
    </region>
  </continent>

  <!-- first continent links -->

  <link type="clique">
    <node name="venus1"/>
    <node name="venus2"/>
    <node name="tellus1"/>
    <node name="tellus2"/>
  </link>

  <link type="line">
    <node name="venus1"/>
    <node name="mercury"/>
    <node name="venus2"/>
  </link>

  <!-- second continent links -->

  <link type="clique">
    <node name="mars1"/>
    <node name="mars2"/>
    <node name="jupiter2"/>
    <node name="jupiter4"/>
  </link>
  <link type="line">
    <node name="jupiter3"/>
    <node name="jupiter1"/>
    <node name="jupiter5"/>
  </link>
  <link type="circle">
    <node name="jupiter2"/>
    <node name="jupiter1"/>
    <node name="jupiter4"/>
  </link>
  <link type="line">
    <node name="jupiter2"/>
    <node name="jupiter3"/>
  </link>
  <link type="line">
    <node name="jupiter4"/>
    <node name="jupiter5"/>
  </link>
  <!-- third continent links -->
  <link type="circle">
    <node name="saturn1"/>
    <node name="saturn2"/>
    <node name="saturn3"/>
  </link>
  <link type="circle">
    <node name="uranus1"/>
    <node name="uranus2"/>
    <node name="uranus3"/>
  </link>
  <link type="line">
    <node name="uranus1"/>
    <node name="saturn2"/>
    <node name="uranus3"/>
  </link>

  <!-- fourth continent links -->
  <link type="circle">
    <node name="deathstar1"/>
    <node name="deathstar2"/>
    <node name="deathstar3"/>
  </link>
  <link type="circle">
    <node name="neptune1"/>
    <node name="neptune2"/>
    <node name="pluto"/>
  </link>
  <link type="line">
    <node name="neptune2"/>
    <node name="deathstar2"/>
    <node name="pluto"/>
  </link>
 <!-- intercontinental links -->
  <link type="clique">
    <node name="mars1"/>
    <node name="mars2"/>
    <node name="tellus1"/>
    <node name="tellus2"/>
  </link>
  <link type="clique">
    <node name="jupiter3"/>
    <node name="jupiter5"/>
    <node name="saturn1"/>
    <node name="saturn3"/>
  </link>
  <link type="line">
    <node name="neptune1"/>
    <node name="uranus2"/>
    <node name="neptune2"/>
  </link>
  <link type="line">
    <node name="pluto"/>
    <node name="mercury"/>
  </link>
  <link type="line">
    <node name="deathstar3"/>
    <node name="jupiter5"/>
  </link>
  <link type="line">
    <node name="uranus3"/>
    <node name="deathstar2"/>
    <node name="saturn3"/>
  </link>
  
</map>

=== arximboldi/jagsat/doc/map/worldmap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map SYSTEM "doc/file-formats/map-file.dtd">

<map bg="world.png">
  <meta>
    <author>Thomas Forss</author>
    <description>Made the continent reinforcements 2,3,4,5,6,7 (can easliy be changed) </description>
  </meta>


  <!-- continent europe -->

  <continent name="europe"
	     troops="5">
    <region name="spain">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="balkan">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="united kingdom">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="western europe">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>   
    <region name="eastern europe">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="scandinavia">
      <polygon>
	<point x="10" y="20"/>
      </polygon>
    </region>
    <region name="iceland">
      <polygon>
	<point x="10" y="20"/>
      </polygon>
    </region>
    <region name="st. petersburg">
      <polygon>
	<point x="10" y="20"/>
      </polygon>
    </region>
  </continent>

  <!-- continent north america -->

  <continent name="north amerika"
	     troops="6">
    <region name="alaska">
      <polygon>
	<point x="10" y="20"/>
      </polygon>
    </region>
    <region name="western canada">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="eastern canada">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="northern canada">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="greenland">
      <polygon>
	<point x="10" y="20"/>
      </polygon>
    </region>
    <region name="california">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>   
    <region name="texas">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="florida">
      <polygon>
	<point x="10" y="20"/>
      </polygon>
    </region>
    <region name="new york">
      <polygon>
	<point x="10" y="20"/>
      </polygon>
    </region>
    <region name="mexico">
      <polygon>
	<point x="10" y="20"/>
      </polygon>
    </region>
  </continent>

  <!-- continent south america -->

  <continent name="south america"
	     troops="3">
    <region name="venezuela">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="colombia">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="brazil">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="peru">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>   
    <region name="argentina">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
  </continent>


  <!-- continent africa -->

  <continent name="africa"
	     troops="4">
    <region name="algeria">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="egypt">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="congo">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="south africa">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>   
    <region name="tanzania">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="madagascar">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
  </continent>

  <!-- continent asia -->

  <continent name="asia"
	     troops="7">
    <region name="ural">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="siberia">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="yakutsk">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="chersky">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>   
    <region name="japan">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="china">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="india">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="iran">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="saudi arabia">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="thailand">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="mongolia">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
  </continent>

  <!-- continent australia -->

  <continent name="australia"
	     troops="2">
    <region name="indonesia">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="new guinea">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="western australia">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>
    <region name="eastern australia">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>   
  </continent>

  <!-- continent australia links -->

  <link type="clique">

    <node name="indonesia"/>
    <node name="new guinea"/>
    <node name="western australia"/>
    <node name="eastern australia"/>
  </link>

  <!-- continent south america links -->

  <link type="circle">
    <node name="venezuela"/>
    <node name="colombia"/>
    <node name="brazil"/>
  </link>
  <link type="line">
    <node name="venezuela"/>
    <node name="brazil"/>
  </link>

  <link type="circle">
    <node name="argentina"/>
    <node name="brazil"/>
    <node name="peru"/>
  </link>

  <!-- continent africa links -->

  <link type="line">
    <node name="algeria"/>
    <node name="egypt"/>
    <node name="tanzania"/>
  </link>
  <link type="circle">
    <node name="algeria"/>
    <node name="congo"/>
    <node name="tanzania"/>
  </link>
  <link type="line">
    <node name="south africa"/>
    <node name="congo"/>
  </link>
  <link type="circle">
    <node name="south africa"/>
    <node name="madagascar"/>
    <node name="tanzania"/>
  </link>

  <!-- continent north america links -->

  <link type="line">
    <node name="florida"/>
    <node name="mexico"/>
    <node name="texas"/>
  </link>
  <link type="line">
    <node name="northern canada"/>
    <node name="greenland"/>
    <node name="eastern canada"/>
  </link>
  <link type="line">
    <node name="eastern canada"/>
    <node name="new york"/>
  </link>
  <link type="circle">
    <node name="western canada"/>
    <node name="california"/>
    <node name="alaska"/>
  </link>
  <link type="circle">
    <node name="eastern canada"/>
    <node name="northern canada"/>
    <node name="western canada"/>
  </link>
  <link type="circle">
    <node name="eastern canada"/>
    <node name="california"/>
    <node name="texas"/>
  </link>
  <link type="circle">
    <node name="new york"/>
    <node name="florida"/>
    <node name="texas"/>
  </link>

  <!-- continent europe links -->

  <link type="line">
    <node name="eastern europe"/>
    <node name="st. petersburg"/>
  </link>
  <link type="line">
    <node name="spain"/>
    <node name="balkan"/>
  </link>
  <link type="circle">
    <node name="western europe"/>
    <node name="spain"/>
    <node name="united kingdom"/>
  </link>
  <link type="circle">
    <node name="iceland"/>
    <node name="scandinavia"/>
    <node name="united kingdom"/>
  </link>
  <link type="circle">
    <node name="western europe"/>
    <node name="scandinavia"/>
    <node name="st. petersburg"/>
  </link>
  <link type="circle">
    <node name="western europe"/>
    <node name="eastern europe"/>
    <node name="balkan"/>
  </link>

  <!-- continent asia links -->

  <link type="clique">

    <node name="yakutsk"/>
    <node name="chersky"/>
    <node name="mongolia"/>
    <node name="japan"/>
  </link>
  <link type="line">
    <node name="japan"/>
    <node name="china"/>
  </link>

  <link type="line">
    <node name="ural"/>
    <node name="siberia"/>
    <node name="yakutsk"/>
  </link>

  <link type="circle">
    <node name="india"/>
    <node name="iran"/>
    <node name="china"/>
  </link>
  <link type="circle">
    <node name="mongolia"/>
    <node name="siberia"/>
    <node name="china"/>
  </link>
  <link type="circle">
    <node name="india"/>
    <node name="iran"/>
    <node name="saudi arabia"/>
  </link>
  <link type="circle">
    <node name="india"/>
    <node name="thailand"/>
    <node name="china"/>
  </link>

  <!-- intercontinental links -->

  <link type="line">
    <node name="thailand"/>
    <node name="indonesia"/>
  </link>
  <link type="line">
    <node name="chersky"/>
    <node name="alaska"/>
  </link>
  <link type="line">
    <node name="brazil"/>
    <node name="algeria"/>
  </link>
  <link type="line">
    <node name="greenland"/>
    <node name="iceland"/>
  </link>
  <link type="line">
    <node name="colombia"/>
    <node name="mexico"/>
    <node name="venezuela"/>
  </link>
  <link type="line">
    <node name="spain"/>
    <node name="algeria"/>
    <node name="balkan"/>
  </link>
  <link type="line">
    <node name="egypt"/>
    <node name="balkan"/>
    <node name="saudi arabia"/>
  </link>
  <link type="line">
    <node name="iran"/>
    <node name="eastern europe"/>
    <node name="saudi arabia"/>
  </link>
  <link type="line">
    <node name="ural"/>
    <node name="st. petersburg"/>
    <node name="iran"/>
  </link>
  

</map>

=== arximboldi/jagsat/doc/map/galaxymap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map SYSTEM "file:../file-formats/map-file.dtd">

<map bg="doc/map/newmapx2.png" 
     xscale="4" yscale="2.8" xoffset="0" yoffset="150" zoom="2">
  <meta>
    <author>The JAGSAT Development team.</author>
    <description>solarsystem map.</description>
  </meta>

  <!-- continent Starburst -->

  <continent name="Starburst"
	     troops="4">
    <region name="Magellan">
      <circle>
	<point x="128" y="137"/>	<!-- first group starts --> <!-- down in middle -->
      </circle>
    </region>
    <region name="Pinwheel">
      <circle>
	<point x="95" y="135"/>
      </circle>
    </region>
    <region name="Stox">
      <circle>
	<point x="85" y="165"/>
      </circle>
    </region>
    <region name="Entrome">
      <circle>
	<point x="113" y="170"/>
      </circle>
    </region>
    <region name="Mayall's Object">
      <circle>
	<point x="141" y="165"/>	<!-- first group ends -->
      </circle>
    </region>
  </continent>

  <!-- continent Virgo Cluster -->

  <continent name="Virgo Cluster"
	     troops="4">
  
    <region name="Sunflower">
      <circle>
	<point x="45" y="163"/>		<!-- second group starts -->	<!-- left down -->
      </circle>
    </region>
    <region name="Sombrero">
      <circle>
	<point x="41" y="115"/>
      </circle>
    </region>
    <region name="Whirlpool">
      <circle>
	<point x="25" y="137"/>
      </circle>
    </region>
    <region name="Tadpole">
      <circle>
	<point x="33" y="84"/>
      </circle>
    </region>
    <region name="Triangulum">
      <circle>
	<point x="60" y="135"/>		<!-- second group ends -->
      </circle>
    </region>
  </continent>

  <!-- continent Supernova Factory -->

   <continent name="Supernova Factory"
	     troops="4">


    <region name="Sculptor">
      <circle>
	<point x="33" y="47"/>		<!-- third group starts -->	<!-- left up -->
      </circle>
    </region>   
    <region name="Bode">
      <circle>
	<point x="24" y="10"/>  <!-- left second highest -->
      </circle>
    </region>
    <region name="Factory1">
      <circle>
	<point x="50" y="15"/>
      </circle>
    </region>
    <region name="Goldmine">
      <circle>
	<point x="58" y="-12"/>
      </circle>
    </region>
    <region name="Androidfarm">
      <circle>
	<point x="35" y="-18"/>
      </circle>
    </region>
   </continent>

  <!-- continent Andromeda -->

   <continent name="Andromeda"
	     troops="4">


    <region name="Superluminal">
      <circle>
	<point x="91" y="-20"/>		<!-- fourth group starts -->	<!-- middle up-->
      </circle>
    </region>
    <region name="luminar">
      <circle>
	<point x="130" y="-20"/>
      </circle>
    </region>   
    <region name="blazar">
      <circle>
	<point x="153" y="-20"/>
      </circle>
    </region>
    <region name="Canter">
      <circle>
	<point x="115" y="3"/>
      </circle>
    </region>
    <region name="Millius">
      <circle>
	<point x="155" y="15"/>		<!-- fourth group ends -->
      </circle>
    </region>
   </continent>

  <!-- continent Magoo's Palace -->

  <continent name="Magoo's Palace"
	     troops="4">

    <region name="Abandoned">
      <circle>
	<point x="186" y="16"/>		<!-- fifth group starts -->	<!-- right up -->
      </circle>
    </region>
    <region name="neptunel">
      <circle>
	<point x="192" y="-10"/>
      </circle>
    </region>   
   <region name="Sagittaurus">
      <circle>
	<point x="209" y="-25"/>
      </circle>
    </region>
    <region name="Gant">
      <circle>
	<point x="213" y="11"/>
      </circle>
    </region>
    <region name="quasar">
      <circle>
	<point x="209" y="45"/>		<!-- fifth group ends -->
      </circle>
    </region>
   </continent>
  
  <!-- continent Cigar Galaxy -->

  <continent name="Cigar Galaxy"
	     troops="4">
    <region name="Aarseth">
      <circle>
	<point x="212" y="102"/>	<!-- sixth group starts -->	<!-- right down -->
      </circle>
    </region>
    <region name="Abdulla">
      <circle>
	<point x="225" y="131"/>
      </circle>
    </region>
    <region name="Nolan">
      <circle>
	<point x="195" y="131"/>
      </circle>
    </region>
    <region name="Nora">
      <circle>
	<point x="202" y="160"/>
      </circle>
    </region>
    <region name="Rokkosan">
      <circle>
	<point x="175" y="160"/>	<!-- sixth group ends -->
      </circle>
    </region>
   </continent>

  <!-- galaxy links -->

  <link type="clique">
    <node name="Magellan"/>
    <node name="Pinwheel"/>
    <node name="Stox"/>
    <node name="Entrome"/>
    <node name="Mayall's Object"/>
  </link>

  <link type="clique">
    <node name="Sunflower"/>
    <node name="Sombrero"/>
    <node name="Whirlpool"/>
    <node name="Tadpole"/>
    <node name="Triangulum"/>
  </link>

 <link type="clique">
    <node name="Sculptor"/>
    <node name="Bode"/>
    <node name="Factory1"/>
    <node name="Goldmine"/>
    <node name="Androidfarm"/>
  </link>
 
 <link type="clique">
    <node name="Superluminal"/>
    <node name="luminar"/>
    <node name="blazar"/>
    <node name="Canter"/>
    <node name="Millius"/>
  </link>
 <link type="clique">
    <node name="Abandoned"/>
    <node name="neptunel"/>
    <node name="Sagittaurus"/>
    <node name="Gant"/>
    <node name="quasar"/>
  </link>
 <link type="clique">
    <node name="Aarseth"/>
    <node name="Abdulla"/>
    <node name="Nolan"/>
    <node name="Nora"/>
    <node name="Rokkosan"/>
 </link>
  
  <!-- interGalaxy links -->	

  <link type="line">
    <node name="Pinwheel"/>
    <node name="Triangulum"/>
  </link>
    <link type="line">
    <node name="Sunflower"/>
    <node name="Stox"/>
  </link>
    <link type="line">
    <node name="Tadpole"/>
    <node name="Sculptor"/>
  </link>
    <link type="line">
    <node name="Millius"/>
    <node name="Abandoned"/>
  </link>
   <link type="line">
    <node name="quasar"/>
    <node name="Aarseth"/>
  </link>
    <link type="line">
    <node name="Rokkosan"/>
    <node name="Mayall's Object"/>
  </link>
    <link type="line">
    <node name="Goldmine"/>
    <node name="Superluminal"/>
  </link>
</map>

=== arximboldi/jagsat/doc/file-formats/example-map.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map SYSTEM "file:///home/raskolnikov/devel/jagsat/svn/trunk/doc/file-formats/map-file.dtd">

<map bg="world.png">
  <meta>
    <author>John Foo</author>
    <description>Conquer the world!</description>
  </meta>

  <continent name="europe"
	     troops="5">
    <region name="spain">
      <circle>
	<point x="10" y="20"/>
      </circle>
    </region>

    <region name="finland">
      <polygon>
	<point x="10" y="20"/>
      </polygon>
    </region>
  </continent>

  <link type="clique">
    <node name="spain"/>
    <node name="finland"/>
  </link>
</map>
